; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
board_build.partitions = esp32dev_partitions.csv
extra_scripts = pre:scripts/build_fonts.py
lib_extra_dirs = modules
build_flags =
	-I include
	-DCORE_DEBUG_LEVEL=0
	-DU8G2_WITHOUT_FONT_ROTATION
	-DU8G2_WITHOUT_UNICODE
	-DENABLE_DEBUG_LOG=1
	-DDISPLAY_CS_PIN=26
	-DDISPLAY_DC_PIN=5
	-DMAX_BOARDS=6
	-DMAX_KEYS=8

board_build.f_cpu = 240000000L
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain
lib_deps =
	olikraus/U8g2@2.36.5
	bblanchon/ArduinoJson@7.2.0
	squix78/JsonStreamingParser@1.0.5

[env:esp32s3nano]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = arduino_nano_esp32
board_build.partitions = arduino_nano_esp32_partitions.csv
extra_scripts = pre:scripts/build_fonts.py
lib_extra_dirs = modules
build_flags =
	-I include
	-DCORE_DEBUG_LEVEL=0
	-DU8G2_WITHOUT_FONT_ROTATION
	-DU8G2_WITHOUT_UNICODE
	-DENABLE_DEBUG_LOG=1
	-DDISPLAY_CS_PIN=10
	-DDISPLAY_DC_PIN=9
	-DMAX_BOARDS=6
board_build.f_cpu = 240000000L
framework = arduino
monitor_speed = 115200
upload_protocol = esptool

lib_ldf_mode = chain
lib_deps =
	olikraus/U8g2@2.36.5
	bblanchon/ArduinoJson@7.2.0
	squix78/JsonStreamingParser@1.0.5
