; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = esp32dev, esp32s3nano

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
board_build.partitions = esp32dev_partitions.csv
extra_scripts = 
	pre:scripts/build_timestamp.py
	pre:scripts/build_fonts.py
	pre:scripts/auto_build_wasm.py
	pre:scripts/run_web_tests.py
	pre:scripts/portalBuilder.py
	pre:scripts/generate_layouts.py
lib_extra_dirs = modules
build_flags =
	-I src
	-I modules/appContext
	-I modules/webServer
	-I modules/weatherClient
	-I modules/schedulerManager
	-I modules/wifiManager
	-I modules/configManager
	-I modules/displayManager
	-I modules/dataManager
	-I lib/otaUpdater
	-I${PROJECT_PACKAGES_DIR}/framework-arduinoespressif32/libraries/Network/src
	-I${PROJECT_PACKAGES_DIR}/framework-arduinoespressif32/libraries/FS/src
	-DCORE_DEBUG_LEVEL=4
	-DU8G2_WITHOUT_FONT_ROTATION
	-DU8G2_WITHOUT_UNICODE
	-DDISPLAY_CS_PIN=26
	-DDISPLAY_DC_PIN=5
	-DBUTTON_PIN=34
	-DMAX_BOARDS=6
	-DMAX_KEYS=8

board_build.f_cpu = 240000000L
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
	olikraus/U8g2@2.36.5
	bblanchon/ArduinoJson@7.2.0
	squix78/JsonStreamingParser@1.0.5
	mathieucarbou/ESPAsyncWebServer
	HTTPClient

[env:esp32s3nano]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = arduino_nano_esp32
board_build.partitions = arduino_nano_esp32_partitions.csv
extra_scripts = 
	pre:scripts/build_timestamp.py
	pre:scripts/build_fonts.py
	pre:scripts/run_web_tests.py
	pre:scripts/generate_layouts.py
lib_extra_dirs = modules
build_flags =
	-I src
	-I modules/appContext
	-I modules/webServer
	-I modules/weatherClient
	-I modules/schedulerManager
	-I modules/wifiManager
	-I modules/configManager
	-I modules/displayManager
	-I modules/dataManager
	-I lib/otaUpdater
	-I${PROJECT_PACKAGES_DIR}/framework-arduinoespressif32/libraries/Network/src
	-I${PROJECT_PACKAGES_DIR}/framework-arduinoespressif32/libraries/FS/src
	-DCORE_DEBUG_LEVEL=4
	-DU8G2_WITHOUT_FONT_ROTATION
	-DU8G2_WITHOUT_UNICODE
	-DDISPLAY_CS_PIN=10
	-DDISPLAY_DC_PIN=9
	-DBUTTON_PIN=8
	-DMAX_BOARDS=6
	-DMAX_KEYS=4
board_build.f_cpu = 240000000L
framework = arduino
monitor_speed = 115200
upload_protocol = esptool

lib_ldf_mode = deep+
lib_deps =
	olikraus/U8g2@2.36.5
	bblanchon/ArduinoJson@7.2.0
	squix78/JsonStreamingParser@1.0.5
	mathieucarbou/ESPAsyncWebServer

[env:unit_testing_host]
platform = native
build_flags = 
	-std=gnu++17
	-DUNIT_TEST
	-DMAX_BOARDS=6
	-DMAX_KEYS=8
	-I src
	-I test/mocks
	-I modules/appContext
	-I modules/configManager
	-I modules/dataManager
	-I modules/schedulerManager
	-I modules/displayManager
	-I modules/displayManager/widgets
	-I modules/displayManager/boards
	-I modules/displayManager/boards/interfaces
	-I modules/weatherClient
	-I modules/schedulerManager
	-I modules/wifiManager
	-I lib/otaUpdater
	-I .pio/libdeps/unit_testing_host/JsonStreamingParser
	-I .pio/libdeps/unit_testing_host/ArduinoJson/src
lib_compat_mode = strict
lib_deps =
	bblanchon/ArduinoJson@7.2.0
	squix78/JsonStreamingParser@1.0.5

