#!/usr/bin/env python3
"""
Departures Board (c) 2025-2026 Gadec Software
Refactored for v3.0 by Matt McNeill 2026 CB Labs

https://github.com/gadec-uk/departures-board

This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/

Module: tools/layoutsim/scripts/gen_layout_cpp.py
Description: Compiles JSON layout specifications into generated C++ source code for the physical boards.
"""

import json
import os
import sys
import argparse
def update_file_if_changed(filepath, content):
    if os.path.exists(filepath):
        with open(filepath, 'r') as f:
            if f.read() == content:
                return False # Skip write if content is identical
    with open(filepath, 'w') as f:
        f.write(content)
    return True

def gen_layout(json_path):
    """
    Parses a single JSON layout file and generates corresponding `.hpp` and `.cpp` headers for the ESP32.
    Args:
        json_path (str): The absolute or relative path to the `.json` target.
    """
    with open(json_path, 'r') as f:
        data = json.load(f)

    base_name = os.path.basename(json_path).replace('.json', '')
    dir_name = os.path.dirname(json_path)
    
    # Default is NR
    board_type = "NR"
    base_class = "iNationalRailLayout"
    base_include = "../iNationalRailLayout.hpp"
    class_prefix = "layoutNr"

    # Override based on JSON field
    if "boardType" in data:
        bt = data["boardType"].upper()
        if bt == "TFL":
            board_type, base_class, base_include, class_prefix = "TFL", "iTflLayout", "../iTflLayout.hpp", "layoutTfl"
        elif bt == "BUS":
            board_type, base_class, base_include, class_prefix = "Bus", "iBusLayout", "../iBusLayout.hpp", "layoutBus"
        elif bt == "TEST":
            board_type, base_class, base_include, class_prefix = "TEST", "iBoardLayout", "../../interfaces/iBoardLayout.hpp", "layoutTest"
    # Or override based on path
    elif "tflBoard" in json_path:
        board_type, base_class, base_include, class_prefix = "TFL", "iTflLayout", "../iTflLayout.hpp", "layoutTfl"
    elif "busBoard" in json_path:
        board_type, base_class, base_include, class_prefix = "Bus", "iBusLayout", "../iBusLayout.hpp", "layoutBus"
    
    # Mapping from JSON ID to C++ member variable names in base classes
    widget_map = {
        "locationAndFilters": "locationAndFilters",
        "weather": "weather",
        "otaStatus": "otaStatus",
        "wifiWarning": "wifiWarning",
        "services": "servicesWidget",
        "messages": "msgWidget",
        "sysClock": "sysClock",
        "noDataLabel": "noDataLabel",
        "row0Widget": "row0Widget",
        "label": "label",
        "trainFormationWidget": "formationWidget"
    }

    # Clean up base_name for class naming (remove 'layout' prefix if it exists)
    clean_name = base_name
    if clean_name.startswith("layout"):
        clean_name = clean_name[6:]
    
    class_name = class_prefix + clean_name[0].upper() + clean_name[1:]
    guard_name = f"{board_type}_LAYOUT_{clean_name.upper()}_HPP"
    
    widgets = data.get("widgets", [])
    primitives = data.get("primitives", [])

    # --- Generate HPP ---
    hpp_content = f"""/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from {os.path.basename(json_path)}
 */

#ifndef {guard_name}
#define {guard_name}

#include "{base_include}"

class {class_name} : public {base_class} {{
public:
    {class_name}(appContext* context);
    virtual void tick(uint32_t currentMillis) override;
    virtual void render(U8G2& display) override;
    virtual void renderAnimationUpdate(U8G2& display, uint32_t currentMillis) override;
}};

#endif // {guard_name}
"""

    hpp_output_path = os.path.join(dir_name, base_name + ".hpp")
    updated_hpp = update_file_if_changed(hpp_output_path, hpp_content)

    # --- Generate CPP ---
    constructor_body = []
    column_setup = []
    
    # First pass: Process widgets for the constructor (always needed)
    present_widgets = set()
    for w in widgets:
        json_id = w["id"]
        wid = widget_map.get(json_id, json_id)
        present_widgets.add(wid)
        
        # Extracted coordinates from geometry block if present
        geom = w.get("geometry", w)
        if "x" in geom and "y" in geom:
            x, y = geom["x"], geom["y"]
            width = geom.get("w", -1)
            height = geom.get("h", -1)
            constructor_body.append(f"    {wid}.setCoords({x}, {y}, {width}, {height});")
        
        if "visible" in w:
            vis = "true" if w["visible"] else "false"
            constructor_body.append(f"    {wid}.setVisible({vis});")
            
        if "font" in w:
            constructor_body.append(f"    {wid}.setFont({w['font']});")
            
        if "text" in w:
            constructor_body.append(f"    {wid}.setText(\"{w['text']}\");")
            
        if "blink" in w:
            blink = "true" if w["blink"] else "false"
            constructor_body.append(f"    {wid}.setBlink({blink});")

        if "format" in w:
            # Assuming clockWidget since it's the only one using 'format' right now
            constructor_body.append(f"    {wid}.setFormat(clockWidget::ClockFormat::{w['format']});")

        if "secondaryFont" in w:
            constructor_body.append(f"    {wid}.setSecondaryFont({w['secondaryFont']});")

        if (json_id == "services" or json_id == "servicesWidget" or json_id == "row0Widget") and "columns" in w:
            cols = w["columns"]
            column_setup.append(f"    {{\n")
            column_setup.append(f"        ColumnDef defs[{len(cols)}] = {{\n")
            for c in cols:
                align = c['align']
                align_str = "LEFT"
                if align == 1: align_str = "CENTER"
                elif align == 2: align_str = "RIGHT"
                column_setup.append(f"            {{{c['width']}, TextAlign::{align_str}}},\n")
            column_setup.append("        };\n")
            column_setup.append(f"        {wid}.setColumns({len(cols)}, defs);\n")
            column_setup.append(f"    }}\n")

        if "skipRows" in w or "maxRows" in w:
            skip = w.get("skipRows", 0)
            max_r = w.get("maxRows", -1)
            constructor_body.append(f"    {wid}.setDataLimits({skip}, {max_r});")

        if "scrollDurationMs" in w:
            constructor_body.append(f"    {wid}.setScrollDuration({w['scrollDurationMs']});")
            
        if "align" in w:
            wtype = w.get("type", "")
            if wtype == "labelWidget" or wtype == "clockWidget":
                constructor_body.append(f"    {wid}.setAlignment({w['align']});")
        
        if "scrollDwellMs" in w:
            constructor_body.append(f"    {wid}.setScrollDwell({w['scrollDwellMs']});")

    # Pass 1.5: Disable visibility for natively mapped widgets not specified in the JSON
    if board_type == "NR":
        nr_superset = {"locationAndFilters", "weather", "wifiWarning", "sysClock", "row0Widget", "servicesWidget", "msgWidget", "noDataLabel", "formationWidget"}
        for wid in sorted(nr_superset):
            if wid not in present_widgets:
                constructor_body.append(f"    {wid}.setVisible(false);")

    # Second pass: Generate tick, render, and animation calls in JSON order
    render_calls = []
    tick_calls = []
    animation_calls = []
    
    for key, elements in data.items():
        if key == "widgets":
            for w in elements:
                wid = widget_map.get(w["id"], w["id"])
                render_calls.append(f"    {wid}.render(display);")
                tick_calls.append(f"    {wid}.tick(currentMillis);")
                animation_calls.append(f"    {wid}.renderAnimationUpdate(display, currentMillis);")
        elif key == "primitives":
            for p in elements:
                ptype = p["type"]
                geom = p["geometry"]
                if ptype == "line":
                    render_calls.append(f"    display.drawLine({geom['x1']}, {geom['y1']}, {geom['x2']}, {geom['y2']});")
                elif ptype == "box":
                    is_filled = p.get("isFilled", True)
                    if is_filled:
                        render_calls.append(f"    display.drawBox({geom['x']}, {geom['y']}, {geom['w']}, {geom['h']});")
                    else:
                        render_calls.append(f"    display.drawFrame({geom['x']}, {geom['y']}, {geom['w']}, {geom['h']});")
                elif ptype == "text":
                    text = p.get("text", "")
                    font = p.get("font", "nullptr")
                    align_val = p.get("align", 0)
                    if align_val == 0 or align_val == "LEFT": align_str = "LEFT"
                    elif align_val == 1 or align_val == "CENTER": align_str = "CENTER"
                    elif align_val == 2 or align_val == "RIGHT": align_str = "RIGHT"
                    else: align_str = "LEFT"
                    truncate = "true" if p.get("truncate", False) else "false"
                    x, y = geom.get("x", 0), geom.get("y", 0)
                    w, h = geom.get("w", -1), geom.get("h", -1)
                    render_calls.append(f"    drawText(display, \"{text}\", {x}, {y}, {w}, {h}, TextAlign::{align_str}, {truncate}, {font});")
    
    render_method = f"""
void {class_name}::tick(uint32_t currentMillis) {{
{chr(10).join(tick_calls)}
}}

void {class_name}::render(U8G2& display) {{
{chr(10).join(render_calls)}
}}

void {class_name}::renderAnimationUpdate(U8G2& display, uint32_t currentMillis) {{
{chr(10).join(animation_calls)}
}}
"""

    cpp_lines = [
        f"/*",
        f" * Departures Board (c) 2025-2026 Gadec Software",
        f" * Autogenerated from {os.path.basename(json_path)}",
        f" */",
        "",
        f"#include \"{base_name}.hpp\"",
        f"#include <displayManager.hpp>",
        f"#include <fonts/fonts.hpp>",
        "",
        f"{class_name}::{class_name}(appContext* context) ",
        f"    : {base_class}(context) {{",
        ""
    ]
    
    cpp_lines.extend(constructor_body)
    cpp_lines.extend(column_setup)
    cpp_lines.append("}")
    cpp_lines.append(render_method)
    
    cpp_output_path = os.path.join(dir_name, base_name + ".cpp")
    updated_cpp = update_file_if_changed(cpp_output_path, "\n".join(cpp_lines))

    if updated_hpp or updated_cpp:
        print(f"Generated {class_name} (.hpp/.cpp) in {dir_name}")
    else:
        print(f"Layout {class_name} is up to date.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Generate C++ layout from JSON.')
    parser.add_argument('--input', required=True, help='Path to layout.json')
    args = parser.parse_args()
    gen_layout(args.input)
