#!/usr/bin/env python3
import json
import os
import sys
import argparse

def gen_layout(json_path):
    with open(json_path, 'r') as f:
        data = json.load(f)

    base_name = os.path.basename(json_path).replace('.json', '')
    dir_name = os.path.dirname(json_path)
    
    # Default is NR
    board_type = "NR"
    base_class = "iNationalRailLayout"
    base_include = "../iNationalRailLayout.hpp"
    class_prefix = "layoutNr"

    # Override based on JSON field
    if "boardType" in data:
        bt = data["boardType"].upper()
        if bt == "TFL":
            board_type, base_class, base_include, class_prefix = "TFL", "iTflLayout", "../iTflLayout.hpp", "layoutTfl"
        elif bt == "BUS":
            board_type, base_class, base_include, class_prefix = "Bus", "iBusLayout", "../iBusLayout.hpp", "layoutBus"
    # Or override based on path
    elif "tflBoard" in json_path:
        board_type, base_class, base_include, class_prefix = "TFL", "iTflLayout", "../iTflLayout.hpp", "layoutTfl"
    elif "busBoard" in json_path:
        board_type, base_class, base_include, class_prefix = "Bus", "iBusLayout", "../iBusLayout.hpp", "layoutBus"
    
    # Mapping from JSON ID to C++ member variable names in base classes
    widget_map = {
        "header": "headWidget",
        "services": "servicesWidget",
        "messages": "msgWidget",
        "sysClock": "sysClock",
        "noDataLabel": "noDataLabel",
        "row0Time": "row0Time",
        "row0Dest": "row0Dest",
        "label": "label"
    }

    # Clean up base_name for class naming (remove 'layout' prefix if it exists)
    clean_name = base_name
    if clean_name.startswith("layout"):
        clean_name = clean_name[6:]
    
    class_name = class_prefix + clean_name[0].upper() + clean_name[1:]
    guard_name = f"{board_type}_LAYOUT_{clean_name.upper()}_HPP"
    
    widgets = data.get("widgets", [])
    primitives = data.get("primitives", [])

    # --- Generate HPP ---
    hpp_content = f"""/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from {os.path.basename(json_path)}
 */

#ifndef {guard_name}
#define {guard_name}

#include "{base_include}"

class {class_name} : public {base_class} {{
public:
    {class_name}(appContext* context);
}};

#endif // {guard_name}
"""

    with open(os.path.join(dir_name, base_name + ".hpp"), 'w') as f:
        f.write(hpp_content)

    # --- Generate CPP ---
    widget_setup = []
    column_setup = ""
    
    for w in widgets:
        json_id = w["id"]
        wid = widget_map.get(json_id, json_id)
        
        if "x" in w and "y" in w:
            x, y = w["x"], w["y"]
            width = w.get("w", -1)
            height = w.get("h", -1)
            widget_setup.append(f"    {wid}.setCoords({x}, {y}, {width}, {height});")
        
        if "visible" in w:
            vis = "true" if w["visible"] else "false"
            widget_setup.append(f"    {wid}.setVisible({vis});")
            
        if "font" in w:
            widget_setup.append(f"    {wid}.setFont({w['font']});")
            
        if "text" in w:
            widget_setup.append(f"    {wid}.setText(\"{w['text']}\");")
            
        if "blink" in w:
            blink = "true" if w["blink"] else "false"
            if wid == "headWidget":
                widget_setup.append(f"    {wid}.getClock().setBlink({blink});")
            else:
                widget_setup.append(f"    {wid}.setBlink({blink});")

        if json_id == "services" and "columns" in w:
            cols = w["columns"]
            column_setup = f"    ColumnDef cols[{len(cols)}] = {{\n"
            for c in cols:
                column_setup += f"        {{{c['width']}, {c['align']}}},\n"
            column_setup += "    };\n"
            column_setup += f"    {wid}.setColumns({len(cols)}, cols);"

    render_calls = []
    for p in primitives:
        ptype = p["type"]
        if ptype == "line":
            render_calls.append(f"    display.drawLine({p['x1']}, {p['y1']}, {p['x2']}, {p['y2']});")
        elif ptype == "box":
            render_calls.append(f"    display.drawBox({p['x']}, {p['y']}, {p['w']}, {p['h']});")
        elif ptype == "text":
            if "font" in p:
                render_calls.append(f"    display.setFont({p['font']});")
            render_calls.append(f"    display.drawStr({p['x']}, {p['y']}, \"{p['text']}\");")

    render_method = ""
    if render_calls:
        render_method = f"""
void {class_name}::render(U8G2& display) {{
    {base_class}::render(display);
    
{chr(10).join(render_calls)}
}}
"""

    cpp_content = f"""/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from {os.path.basename(json_path)}
 */

#include "{base_name}.hpp"
#include <displayManager.hpp>

{class_name}::{class_name}(appContext* context) 
    : {base_class}(context) {{
    
{os.linesep.join(widget_setup)}

{column_setup}
}}
{render_method}
"""

    with open(os.path.join(dir_name, base_name + ".cpp"), 'w') as f:
        f.write(cpp_content)

    print(f"Generated {class_name} (.hpp/.cpp) in {dir_name}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Generate C++ layout from JSON.')
    parser.add_argument('--input', required=True, help='Path to layout.json')
    args = parser.parse_args()
    gen_layout(args.input)
