#!/usr/bin/env python3
"""
Departures Board (c) 2025-2026 Gadec Software
Refactored for v3.0 by Matt McNeill 2026 CB Labs

https://github.com/gadec-uk/departures-board

This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/

Module: tools/layoutsim/scripts/gen_sim_registry.py
Description: Scans hardware board layout headers and generates a C++ WASM registry loader.
This ensures the simulator's JSON designer perfectly mirrors the physical C++ layout constraints.
"""

import os
import glob
import re

BOARD_DIR = os.path.join("modules", "displayManager", "boards")
OUT_FILE = os.path.join("tools", "layoutsim", "src", "generated_registry.hpp")

# Known widget types we expect to find in headers
WIDGET_TYPES = {
    "stationName": "labelWidget(0, 0, 10, 10)",
    "filterInfo": "scrollingTextWidget(0, 0, 10, 10)",
    "weatherWidget": "weatherWidget(&g_appContext, 0, 0, 10, 10)",
    "wifiStatusWidget": "wifiStatusWidget(0, 0)",
    "serviceListWidget": "serviceListWidget(0, 0, 10, 10)",
    "scrollingMessagePoolWidget": "scrollingMessagePoolWidget(0, 0, 10, 10)",
    "labelWidget": "labelWidget(0, 0, 10, 10)",
    "clockWidget": "clockWidget(tm, 0, 0, 10, 10)",
    "scrollingTextWidget": "scrollingTextWidget(0, 0, 10, 10)",
    "locationAndFiltersWidget": "locationAndFiltersWidget(0, 0, 10, 10)",
    "trainFormationWidget": "trainFormationWidget(0, 0, 10, 10)"
}

def main():
    """
    Primary orchestration method. Scans all targeted repository directories and parses header structures.
    """
    headers = glob.glob(os.path.join(BOARD_DIR, "*", "i*Layout.hpp"))
    
    layouts = {}
    
    hashes = []
    for header in sorted(headers):
        with open(header, "r") as f:
            content = f.read()
            
        # Find the class name (e.g., class iNationalRailLayout : public iBoardLayout)
        class_match = re.search(r"class\s+(i[A-Za-z0-9_]+Layout)\s*:", content)
        if not class_match:
            continue
            
        layout_name_raw = class_match.group(1)
        
        # Keep the raw class name to exactly match the JSON layout property
        clean_name = layout_name_raw
            
        layouts[clean_name] = []
        
        # Find widget instantiations
        for line in content.split("\n"):
            line = line.strip()
            # Match things like "headerWidget headWidget;"
            m = re.match(r"^([a-zA-Z0-9_]+Widget)\s+([a-zA-Z0-9_]+)\s*;", line)
            if m:
                w_type = m.group(1)
                w_name = m.group(2)
                if w_type in WIDGET_TYPES:
                    layouts[clean_name].append((w_type, w_name))
                else:
                    import sys
                    print(f"\n[!] FATAL SIMULATOR BUILD ERROR [!]")
                    print(f"Widget type '{w_type}' (found in {clean_name}) is NOT mapped in WASM registry!")
                    print(f"To fix: Add it to WIDGET_TYPES in tools/layoutsim/scripts/gen_sim_registry.py")
                    print(f"        AND to the enum list in tools/layoutsim/layout.schema.json")
                    sys.exit(1)
        
        # Add content to hashes (simple version for now)
        hashes.append(content)

    # Add the script itself to the hash calculation
    with open(__file__, "r") as f:
        hashes.append(f.read())

    import hashlib
    combined = "".join(hashes).encode()
    final_hash = hashlib.md5(combined).hexdigest()

    generate_cpp(layouts, final_hash)

def generate_cpp(layouts, registry_hash):
    """
    Outputs the aggregated layout maps via a templated C++ string into generated_registry.hpp.
    Args:
        layouts (dict): Formatted dictionary mapping layout names to their array of widgets.
        registry_hash (str): MD5 hash of all input files used to generate this registry.
    """
    cpp = """// AUTO-GENERATED BY gen_sim_registry.py. DO NOT EDIT.
// Registry Hash: {{REGISTRY_HASH}}
#pragma once
#include <string>
#include <vector>
#include <vector>
#include "designerRegistry.hpp"
#include "labelWidget.hpp"
#include "scrollingTextWidget.hpp"
#include "locationAndFiltersWidget.hpp"
#include "serviceListWidget.hpp"
#include "scrollingMessagePoolWidget.hpp"
#include "clockWidget.hpp"
#include "weatherWidget.hpp"
#include "wifiStatusWidget.hpp"
#include "trainFormationWidget.hpp"
#include "timeManager.hpp"
#include "messagePool.hpp"
#include "appContext.hpp"

#define SIM_REGISTRY_HASH "{{REGISTRY_HASH}}"

// We store active pointers here so we can safely delete them on profile swap.
static std::vector<iGfxWidget*> g_activeProfileWidgets;

inline void loadLayoutProfile(const std::string& layoutName, TimeManager* tm, MessagePool* mp) {
    DesignerRegistry::getInstance().clear();
    for(auto w : g_activeProfileWidgets) {
        delete w;
    }
    g_activeProfileWidgets.clear();

"""
    cpp = cpp.replace("{{REGISTRY_HASH}}", registry_hash)
    
    first = True
    for layout_name, widgets in layouts.items():
        if first:
            cpp += f'    if (layoutName == "{layout_name}") {{\n'
            first = False
        else:
            cpp += f'    }} else if (layoutName == "{layout_name}") {{\n'
            
        for w_type, w_name in widgets:
            constructor = WIDGET_TYPES[w_type]
            cpp += f'        auto w_{w_name} = new {constructor};\n'
            # Hook up specific mock data deps
            if w_type == "scrollingMessagePoolWidget":
                cpp += f'        w_{w_name}->addMessagePool(mp);\n'
                
            cpp += f'        DesignerRegistry::getInstance().registerWidget("{w_name}", w_{w_name}, "{w_type}");\n'
            cpp += f'        g_activeProfileWidgets.push_back(w_{w_name});\n\n'
            
    cpp += "    }\n}\n"
    
    # Also generate a helper function to render and tick exactly the active widgets
    cpp += """
inline void tickActiveProfile(uint32_t currentMillis) {
    for(auto w : g_activeProfileWidgets) {
        w->tick(currentMillis);
    }
}

inline void renderActiveProfile(U8G2& display) {
    for(auto w : g_activeProfileWidgets) {
        if(w->getVisible()) {
            w->render(display);
        }
    }
}
"""

    with open(OUT_FILE, "w") as f:
        f.write(cpp)
        
    print(f"Generated {OUT_FILE} with {len(layouts)} layout profiles.")

if __name__ == "__main__":
    main()
