#!/usr/bin/env python3
import sys
import gzip
import os

def convert_to_progmem(input_file):
    if not os.path.exists(input_file):
        print(f"Error: File {input_file} not found.")
        sys.exit(1)

    # Standardize filename for C++ variable naming
    # Using snake_case for variables as is common in the PROGMEM pattern, 
    # but the file name itself follows camelCase (convertToProgmem.py)
    basename = os.path.basename(input_file)
    name_part, ext_part = os.path.splitext(basename)
    clean_name = name_part.replace('.', '_').replace('-', '_')
    ext_name = ext_part.replace('.', '_')
    var_name = f"{clean_name}{ext_name}_gz"
    output_file = f"{var_name}.h"

    # Read and compress the file
    with open(input_file, 'rb') as f_in:
        raw_data = f_in.read()
        compressed_data = gzip.compress(raw_data)

    # Format as C++ hex array
    hex_array = ', '.join([f'0x{b:02X}' for b in compressed_data])
    
    # Split hex array into lines of 12 for readability
    hex_lines = []
    hex_items = [f'0x{b:02X}' for b in compressed_data]
    for i in range(0, len(hex_items), 12):
        hex_lines.append('    ' + ', '.join(hex_items[i:i+12]))
    formatted_hex = ',\n'.join(hex_lines)

    header_content = f"""/*
 * Auto-generated by Antigravity Agent Skill (embedded-web-designer)
 * Original File: {basename}
 * Original Size: {len(raw_data)} bytes
 * Compressed Size: {len(compressed_data)} bytes
 */

#pragma once
#include <Arduino.h>

const size_t {var_name}_len = {len(compressed_data)};
const uint8_t {var_name}[] PROGMEM = {{
{formatted_hex}
}};
"""
    with open(output_file, 'w') as f_out:
        f_out.write(header_content)
    print(f"Success: Generated {output_file} ({len(compressed_data)} bytes compressed).")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 convertToProgmem.py <file.html>")
        sys.exit(1)
    convert_to_progmem(sys.argv[1])
