/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from layoutReplica.json
 */

#include "layoutReplica.hpp"
#include <displayManager.hpp>

layoutNrReplica::layoutNrReplica(appContext* context) 
    : iNationalRailLayout(context) {
    
    msgWidget.setCoords(0, 0, 200, 12);
    msgWidget.setVisible(true);
    msgWidget.setFont(NatRailSmall9);
    sysClock.setCoords(200, 0, 56, 12);
    sysClock.setVisible(true);
    row0Widget.setCoords(0, 12, 256, 14);
    row0Widget.setVisible(true);
    row0Widget.setDataLimits(0, 1);
    row0Widget.setFont(NatRailTall12);
    servicesWidget.setCoords(0, 26, 256, 38);
    servicesWidget.setVisible(true);
    headWidget.setVisible(false);
    noDataLabel.setCoords(10, 40, 256, 15);
    noDataLabel.setVisible(false);
    noDataLabel.setFont(NatRailTall12);
    noDataLabel.setText("No services found.");

    ColumnDef cols[4] = {
        {20, 0},
        {35, 0},
        {25, 2},
        {176, 0},
    };
    servicesWidget.setColumns(4, cols);
    servicesWidget.setDataLimits(1, -1);

    ColumnDef row0Cols[4] = {
        {0, 0},
        {60, 0},
        {0, 0},
        {196, 0},
    };
    row0Widget.setColumns(4, row0Cols);
}

