/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from layoutDefault.json
 */

#ifndef NR_LAYOUT_DEFAULT_HPP
#define NR_LAYOUT_DEFAULT_HPP

#include "../iNationalRailLayout.hpp"

class layoutNrDefault : public iNationalRailLayout {
public:
    layoutNrDefault(appContext* context);
};

#endif // NR_LAYOUT_DEFAULT_HPP
