/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from layoutReplica.json
 */

#ifndef NR_LAYOUT_REPLICA_HPP
#define NR_LAYOUT_REPLICA_HPP

#include "../iNationalRailLayout.hpp"

class layoutNrReplica : public iNationalRailLayout {
public:
    layoutNrReplica(appContext* context);
};

#endif // NR_LAYOUT_REPLICA_HPP
