/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from layoutReplica.json
 */

#include "layoutReplica.hpp"
#include <displayManager.hpp>

layoutNrReplica::layoutNrReplica(appContext* context) 
    : iNationalRailLayout(context) {
    
    msgWidget.setCoords(0, 0, 200, 12);
    msgWidget.setVisible(true);
    msgWidget.setFont(NatRailSmall9);
    sysClock.setCoords(200, 0, 56, 12);
    sysClock.setVisible(true);
    row0Time.setCoords(0, 12, 60, 14);
    row0Time.setVisible(true);
    row0Time.setFont(NatRailTall12);
    row0Dest.setCoords(60, 12, 196, 14);
    row0Dest.setVisible(true);
    row0Dest.setFont(NatRailTall12);
    servicesWidget.setCoords(0, 26, 256, 38);
    servicesWidget.setVisible(true);
    headWidget.setVisible(false);
    noDataLabel.setCoords(10, 40, 256, 15);
    noDataLabel.setVisible(false);
    noDataLabel.setFont(NatRailTall12);
    noDataLabel.setText("No services found.");

    ColumnDef cols[4] = {
        {20, 0},
        {35, 0},
        {25, 2},
        {176, 0},
    };
    servicesWidget.setColumns(4, cols);
}

