/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from layoutDefault.json
 */

#include "layoutDefault.hpp"
#include <displayManager.hpp>

layoutNrDefault::layoutNrDefault(appContext* context) 
    : iNationalRailLayout(context) {
    
    headWidget.setCoords(0, 0, 256, 12);
    headWidget.setVisible(true);
    row0Widget.setCoords(0, 12, 256, 14);
    row0Widget.setVisible(true);
    row0Widget.setDataLimits(0, 1);
    row0Widget.setFont(NatRailTall12);
    servicesWidget.setCoords(0, 26, 256, 39);
    servicesWidget.setVisible(true);
    msgWidget.setCoords(0, 52, 256, 12);
    msgWidget.setVisible(true);
    msgWidget.setFont(NatRailSmall9);
    sysClock.setVisible(false);
    noDataLabel.setCoords(10, 40, 256, 15);
    noDataLabel.setVisible(false);
    noDataLabel.setFont(NatRailTall12);
    noDataLabel.setText("No services found.");

    ColumnDef cols[4] = {
        {23, 0},
        {27, 0},
        {16, 1},
        {190, 0},
    };
    servicesWidget.setColumns(4, cols);
    servicesWidget.setDataLimits(1, -1);

    ColumnDef row0Cols[4] = {
        {0, 0},
        {60, 0},
        {0, 0},
        {196, 0},
    };
    row0Widget.setColumns(4, row0Cols);
}

