/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from layoutDefault.json
 */

#include "layoutDefault.hpp"
#include <displayManager.hpp>

layoutBusDefault::layoutBusDefault(appContext* context) 
    : iBusLayout(context) {
    
    headWidget.setCoords(0, 0, 256, 12);
    headWidget.setVisible(true);
    headWidget.setFont(Underground10);
    headWidget.getClock().setBlink(true);
    servicesWidget.setCoords(0, 12, 256, 39);
    servicesWidget.setVisible(true);
    msgWidget.setCoords(0, 52, 256, 12);
    msgWidget.setVisible(true);
    noDataLabel.setCoords(10, 35, 256, 15);
    noDataLabel.setVisible(false);
    noDataLabel.setFont(Underground10);
    noDataLabel.setText("No scheduled services.");

    ColumnDef cols[3] = {
        {25, 0},
        {180, 0},
        {51, 2},
    };
    servicesWidget.setColumns(3, cols);
}

