/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from layoutDefault.json
 */

#ifndef Bus_LAYOUT_DEFAULT_HPP
#define Bus_LAYOUT_DEFAULT_HPP

#include "../iBusLayout.hpp"

class layoutBusDefault : public iBusLayout {
public:
    layoutBusDefault(appContext* context);
};

#endif // Bus_LAYOUT_DEFAULT_HPP
