// AUTO-GENERATED BY gen_sim_registry.py. DO NOT EDIT.
#pragma once
#include <string>
#include <vector>
#include "designerRegistry.hpp"
#include "headerWidget.hpp"
#include "serviceListWidget.hpp"
#include "scrollingMessagePoolWidget.hpp"
#include "labelWidget.hpp"
#include "clockWidget.hpp"
#include "scrollingTextWidget.hpp"
#include "timeManager.hpp"
#include "messagePool.hpp"

// We store active pointers here so we can safely delete them on profile swap.
static std::vector<iGfxWidget*> g_activeProfileWidgets;

inline void loadLayoutProfile(const std::string& layoutName, TimeManager* tm, MessagePool* mp) {
    DesignerRegistry::getInstance().clear();
    for(auto w : g_activeProfileWidgets) {
        delete w;
    }
    g_activeProfileWidgets.clear();

    if (layoutName == "iTflLayout") {
        auto w_headWidget = new headerWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("headWidget", w_headWidget);
        g_activeProfileWidgets.push_back(w_headWidget);

        auto w_servicesWidget = new serviceListWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("servicesWidget", w_servicesWidget);
        g_activeProfileWidgets.push_back(w_servicesWidget);

        auto w_msgWidget = new scrollingMessagePoolWidget(0, 0, 10, 10);
        w_msgWidget->addMessagePool(mp);
        DesignerRegistry::getInstance().registerWidget("msgWidget", w_msgWidget);
        g_activeProfileWidgets.push_back(w_msgWidget);

        auto w_noDataLabel = new labelWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("noDataLabel", w_noDataLabel);
        g_activeProfileWidgets.push_back(w_noDataLabel);

    } else if (layoutName == "iBusLayout") {
        auto w_headWidget = new headerWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("headWidget", w_headWidget);
        g_activeProfileWidgets.push_back(w_headWidget);

        auto w_servicesWidget = new serviceListWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("servicesWidget", w_servicesWidget);
        g_activeProfileWidgets.push_back(w_servicesWidget);

        auto w_msgWidget = new scrollingMessagePoolWidget(0, 0, 10, 10);
        w_msgWidget->addMessagePool(mp);
        DesignerRegistry::getInstance().registerWidget("msgWidget", w_msgWidget);
        g_activeProfileWidgets.push_back(w_msgWidget);

        auto w_noDataLabel = new labelWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("noDataLabel", w_noDataLabel);
        g_activeProfileWidgets.push_back(w_noDataLabel);

    } else if (layoutName == "iNationalRailLayout") {
        auto w_headWidget = new headerWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("headWidget", w_headWidget);
        g_activeProfileWidgets.push_back(w_headWidget);

        auto w_row0Time = new scrollingTextWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("row0Time", w_row0Time);
        g_activeProfileWidgets.push_back(w_row0Time);

        auto w_row0Dest = new scrollingTextWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("row0Dest", w_row0Dest);
        g_activeProfileWidgets.push_back(w_row0Dest);

        auto w_servicesWidget = new serviceListWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("servicesWidget", w_servicesWidget);
        g_activeProfileWidgets.push_back(w_servicesWidget);

        auto w_msgWidget = new scrollingMessagePoolWidget(0, 0, 10, 10);
        w_msgWidget->addMessagePool(mp);
        DesignerRegistry::getInstance().registerWidget("msgWidget", w_msgWidget);
        g_activeProfileWidgets.push_back(w_msgWidget);

        auto w_sysClock = new clockWidget(tm, 0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("sysClock", w_sysClock);
        g_activeProfileWidgets.push_back(w_sysClock);

        auto w_noDataLabel = new labelWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("noDataLabel", w_noDataLabel);
        g_activeProfileWidgets.push_back(w_noDataLabel);

    }
}

inline void tickActiveProfile(uint32_t currentMillis) {
    for(auto w : g_activeProfileWidgets) {
        w->tick(currentMillis);
    }
}

inline void renderActiveProfile(U8G2& display) {
    for(auto w : g_activeProfileWidgets) {
        if(w->getVisible()) {
            w->render(display);
        }
    }
}
