// AUTO-GENERATED BY gen_sim_registry.py. DO NOT EDIT.
// Registry Hash: 45cf326de3dd25a07bdfbefd358bb688
#pragma once
#include <string>
#include <vector>
#include <vector>
#include "designerRegistry.hpp"
#include "labelWidget.hpp"
#include "scrollingTextWidget.hpp"
#include "locationAndFiltersWidget.hpp"
#include "serviceListWidget.hpp"
#include "scrollingMessagePoolWidget.hpp"
#include "clockWidget.hpp"
#include "weatherWidget.hpp"
#include "wifiStatusWidget.hpp"
#include "timeManager.hpp"
#include "messagePool.hpp"
#include "appContext.hpp"

#define SIM_REGISTRY_HASH "45cf326de3dd25a07bdfbefd358bb688"

// We store active pointers here so we can safely delete them on profile swap.
static std::vector<iGfxWidget*> g_activeProfileWidgets;

inline void loadLayoutProfile(const std::string& layoutName, TimeManager* tm, MessagePool* mp) {
    DesignerRegistry::getInstance().clear();
    for(auto w : g_activeProfileWidgets) {
        delete w;
    }
    g_activeProfileWidgets.clear();

    if (layoutName == "iBusLayout") {
        auto w_locationAndFilters = new locationAndFiltersWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("locationAndFilters", w_locationAndFilters, "locationAndFiltersWidget");
        g_activeProfileWidgets.push_back(w_locationAndFilters);

        auto w_wifiWarning = new wifiStatusWidget(0, 0);
        DesignerRegistry::getInstance().registerWidget("wifiWarning", w_wifiWarning, "wifiStatusWidget");
        g_activeProfileWidgets.push_back(w_wifiWarning);

        auto w_servicesWidget = new serviceListWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("servicesWidget", w_servicesWidget, "serviceListWidget");
        g_activeProfileWidgets.push_back(w_servicesWidget);

        auto w_msgWidget = new scrollingMessagePoolWidget(0, 0, 10, 10);
        w_msgWidget->addMessagePool(mp);
        DesignerRegistry::getInstance().registerWidget("msgWidget", w_msgWidget, "scrollingMessagePoolWidget");
        g_activeProfileWidgets.push_back(w_msgWidget);

        auto w_noDataLabel = new labelWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("noDataLabel", w_noDataLabel, "labelWidget");
        g_activeProfileWidgets.push_back(w_noDataLabel);

    } else if (layoutName == "iNationalRailLayout") {
        auto w_locationAndFilters = new locationAndFiltersWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("locationAndFilters", w_locationAndFilters, "locationAndFiltersWidget");
        g_activeProfileWidgets.push_back(w_locationAndFilters);

        auto w_weather = new weatherWidget(&g_appContext, 0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("weather", w_weather, "weatherWidget");
        g_activeProfileWidgets.push_back(w_weather);

        auto w_wifiWarning = new wifiStatusWidget(0, 0);
        DesignerRegistry::getInstance().registerWidget("wifiWarning", w_wifiWarning, "wifiStatusWidget");
        g_activeProfileWidgets.push_back(w_wifiWarning);

        auto w_sysClock = new clockWidget(tm, 0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("sysClock", w_sysClock, "clockWidget");
        g_activeProfileWidgets.push_back(w_sysClock);

        auto w_row0Widget = new serviceListWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("row0Widget", w_row0Widget, "serviceListWidget");
        g_activeProfileWidgets.push_back(w_row0Widget);

        auto w_servicesWidget = new serviceListWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("servicesWidget", w_servicesWidget, "serviceListWidget");
        g_activeProfileWidgets.push_back(w_servicesWidget);

        auto w_msgWidget = new scrollingMessagePoolWidget(0, 0, 10, 10);
        w_msgWidget->addMessagePool(mp);
        DesignerRegistry::getInstance().registerWidget("msgWidget", w_msgWidget, "scrollingMessagePoolWidget");
        g_activeProfileWidgets.push_back(w_msgWidget);

        auto w_noDataLabel = new labelWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("noDataLabel", w_noDataLabel, "labelWidget");
        g_activeProfileWidgets.push_back(w_noDataLabel);

    } else if (layoutName == "iTflLayout") {
        auto w_locationAndFilters = new locationAndFiltersWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("locationAndFilters", w_locationAndFilters, "locationAndFiltersWidget");
        g_activeProfileWidgets.push_back(w_locationAndFilters);

        auto w_wifiWarning = new wifiStatusWidget(0, 0);
        DesignerRegistry::getInstance().registerWidget("wifiWarning", w_wifiWarning, "wifiStatusWidget");
        g_activeProfileWidgets.push_back(w_wifiWarning);

        auto w_servicesWidget = new serviceListWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("servicesWidget", w_servicesWidget, "serviceListWidget");
        g_activeProfileWidgets.push_back(w_servicesWidget);

        auto w_msgWidget = new scrollingMessagePoolWidget(0, 0, 10, 10);
        w_msgWidget->addMessagePool(mp);
        DesignerRegistry::getInstance().registerWidget("msgWidget", w_msgWidget, "scrollingMessagePoolWidget");
        g_activeProfileWidgets.push_back(w_msgWidget);

        auto w_noDataLabel = new labelWidget(0, 0, 10, 10);
        DesignerRegistry::getInstance().registerWidget("noDataLabel", w_noDataLabel, "labelWidget");
        g_activeProfileWidgets.push_back(w_noDataLabel);

    }
}

inline void tickActiveProfile(uint32_t currentMillis) {
    for(auto w : g_activeProfileWidgets) {
        w->tick(currentMillis);
    }
}

inline void renderActiveProfile(U8G2& display) {
    for(auto w : g_activeProfileWidgets) {
        if(w->getVisible()) {
            w->render(display);
        }
    }
}
