/*
 * Departures Board (c) 2025-2026 Gadec Software
 *
 * GitHub Client Library - enables checking for latest release and downloading assets to file system
 *
 * https://github.com/gadec-uk/departures-board
 *
 * This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
 * To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
 *
 * Module: lib/githubClient/githubClient.cpp
 * Description: Implementation of the githubClient library.
 *
 * Exported Functions/Classes:
 * - class github: JSON streaming parser and API client for fetching GitHub releases.
 *   - github(): Constructor.
 *   - getLatestRelease(): Polls the GitHub API to fetch latest release metadata.
 *   - getLastError(): Retrieves the last error message from the client.
 *   - accessToken: Attribute for GitHub API authorization.
 *   - releaseId: Attribute storing the ID of the fetched release.
 *   - releaseDescription: Attribute storing the description/name of the release.
 *   - releaseAssets: Attribute storing the number of available assets.
 *   - releaseAssetURL: Attribute array of asset download URLs.
 *   - releaseAssetName: Attribute array of asset names.
 */

#include <githubClient.h>
#include <JsonListener.h>
#include <HTTPClient.h>
#include <WiFiClientSecure.h>
#include <LittleFS.h>
#include <logger.hpp>
#include <md5Utils.h>

github::github(String repository, String token) {
    if (repository!="") apiGetLatestRelease = "/repos/" + repository + "/releases/latest";
    accessToken = token; // Initialise with a GitHub token if the repository is private
}

/**
 * @brief Polls the GitHub API to fetch metadata about the latest release for the repository.
 * @return True if the metadata was successfully fetched and parsed, otherwise false.
 */
bool github::getLatestRelease() {

    strcpy(lastErrorMsg, "");
    JsonStreamingParser parser;
    parser.setListener(this);
    WiFiClientSecure httpsClient;

    httpsClient.setInsecure();
    httpsClient.setTimeout(5000);
    httpsClient.setConnectionTimeout(5000);

    int retryCounter=0; //retry counter
    while((!httpsClient.connect(apiHost, 443)) && (retryCounter < 10)){
        delay(200);
        retryCounter++;
    }
    if (retryCounter>=10) {
        strcpy(lastErrorMsg, "Connection timeout");
        LOG_WARN("SYSTEM", lastErrorMsg);
        return false;
    }

    String request = "GET " + apiGetLatestRelease + F(" HTTP/1.0\r\nHost: ") + String(apiHost) + F("\r\nuser-agent: esp32/1.0\r\nX-GitHub-Api-Version: 2022-11-28\r\nAccept: application/vnd.github+json\r\n");
    if (accessToken.length()) request += "Authorization: Bearer " + String(accessToken) + F("\r\n");
    request += F("Connection: close\r\n\r\n");

    httpsClient.print(request);
    retryCounter=0;
    while(!httpsClient.available()) {
        delay(200);
        retryCounter++;
        if (retryCounter > 25) {
            // no response within 5 seconds so quit
            httpsClient.stop();
            strcpy(lastErrorMsg, "Response timeout");
            LOG_WARN("SYSTEM", lastErrorMsg);
            return false;
        }
    }

    while (httpsClient.connected()) {
        // Parse status code
        String statusLine = httpsClient.readStringUntil('\n');
        if (!statusLine.startsWith(F("HTTP/")) || statusLine.indexOf(F("200 OK")) == -1) {
            httpsClient.stop();

            if (statusLine.indexOf(F("404")) > 0) {
                strncpy(lastErrorMsg, statusLine.c_str(), sizeof(lastErrorMsg) - 1);
                lastErrorMsg[sizeof(lastErrorMsg) - 1] = '\0';
                LOG_ERROR("SYSTEM", lastErrorMsg);
            } else {
                strncpy(lastErrorMsg, statusLine.c_str(), sizeof(lastErrorMsg) - 1);
                lastErrorMsg[sizeof(lastErrorMsg) - 1] = '\0';
                LOG_WARN("SYSTEM", lastErrorMsg);
            }
            return false;
        }
        String line = httpsClient.readStringUntil('\n'); // Read the next line to check for headers
        if (line == "\r") {
            // Headers received
            break;
        }
    }

    bool isBody = false;
    char c;
    releaseId="";
    releaseDescription="";
    releaseAssets=0;
    unsigned long dataReceived = 0;

    unsigned long dataSendTimeout = millis() + 12000UL;
    while((httpsClient.available() || httpsClient.connected()) && (millis() < dataSendTimeout)) {
        while(httpsClient.available()) {
            c = httpsClient.read();
            dataReceived++;
            if (c == '{' || c == '[') isBody = true;
            if (isBody) parser.parse(c);
        }
        delay(5);
    }
    httpsClient.stop();
    if (millis() >= dataSendTimeout) {
        snprintf(lastErrorMsg, sizeof(lastErrorMsg), "Data timeout (%d bytes)", dataReceived);
        LOG_WARN("SYSTEM", lastErrorMsg);
        return false;
    }

    strcpy(lastErrorMsg, "SUCCESS");

    return true;
}

/**
 * @brief Retrieves the last error message generated by the client.
 * @return A string containing the error description (or "SUCCESS").
 */
const char* github::getLastError() {
    return lastErrorMsg;
}

/**
 * @brief JSON whitespace handler.
 * @param c The whitespace char.
 */
void github::whitespace(char c) {}

/**
 * @brief JSON handler triggered at start of document.
 */
void github::startDocument() {
    currentArray = "";
    currentObject = "";
}

/**
 * @brief JSON handler triggered for each object key.
 * @param key The string name of the parsed key.
 */
void github::key(String key) {
    currentKey = key;
}

/**
 * @brief JSON handler triggered for each key value.
 * @param value The scalar string value.
 */
void github::value(String value) {
    if (currentKey == "tag_name") releaseId = value;
    else if ((currentKey == "name") && (currentArray=="")) releaseDescription = value;
    else if ((currentKey == "url") && (currentArray=="assets") && (currentObject!="uploader")) assetURL = value;
    else if ((currentKey == "name") && (currentArray=="assets") && (currentObject!="uploader")) assetName = value;

    if (assetURL.length() && assetName.length() && releaseAssets<MAX_RELEASE_ASSETS) {
        // Save the full asset url to the list
        releaseAssetURL[releaseAssets] = assetURL;
        releaseAssetName[releaseAssets++] = assetName;
        assetURL="";
        assetName="";
    }
}

/**
 * @brief JSON handler triggered when exiting an array.
 */
void github::endArray() {
    currentArray = "";
}

/**
 * @brief JSON handler triggered when exiting an object.
 */
void github::endObject() {
    currentObject = "";
}

/**
 * @brief JSON handler triggered at end of document.
 */
void github::endDocument() {}

/**
 * @brief JSON handler triggered when entering an array.
 */
void github::startArray() {
    currentArray = currentKey;
}

/**
 * @brief JSON handler triggered when entering an object.
 */
void github::startObject() {
    currentObject = currentKey;
}
