/*
 * Departures Board (c) 2025-2026 Gadec Software
 *
 * GitHub Client Library - enables checking for latest release and downloading assets to file system
 *
 * https://github.com/gadec-uk/departures-board
 *
 * This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
 * To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
 *
 * Module: lib/githubClient/githubClient.cpp
 * Description: Implementation of the githubClient library.
 *
 * Exported Functions/Classes:
 * - github::getLatestRelease: Polls the GitHub API to fetch metadata about the latest release.
 * - github::getLastError: Retrieves the last error message generated by the client.
 * - github::whitespace: JSON whitespace handler.
 * - github::startDocument: JSON handler triggered at start of document.
 * - github::key: JSON handler triggered for each object key.
 * - github::value: JSON handler triggered for each key value.
 * - github::endArray: JSON handler triggered when exiting an array.
 * - github::endObject: JSON handler triggered when exiting an object.
 * - github::endDocument: JSON handler triggered at end of document.
 * - github::startArray: JSON handler triggered when entering an array.
 * - github::startObject: JSON handler triggered when entering an object.
 */

#include <githubClient.h>
#include <JsonListener.h>
#include <HTTPClient.h>
#include <WiFiClientSecure.h>
#include <LittleFS.h>
#include <md5Utils.h>

github::github(String repository, String token) {
    if (repository!="") apiGetLatestRelease = "/repos/" + repository + "/releases/latest";
    accessToken = token; // Initialise with a GitHub token if the repository is private
}

/**
 * @brief Polls the GitHub API to fetch metadata about the latest release for the repository.
 * @return True if the metadata was successfully fetched and parsed, otherwise false.
 */
bool github::getLatestRelease() {

    lastErrorMsg = "";
    JsonStreamingParser parser;
    parser.setListener(this);
    WiFiClientSecure httpsClient;

    httpsClient.setInsecure();
    httpsClient.setTimeout(5000);
    httpsClient.setConnectionTimeout(5000);

    int retryCounter=0; //retry counter
    while((!httpsClient.connect(apiHost, 443)) && (retryCounter < 10)){
        delay(200);
        retryCounter++;
    }
    if(retryCounter>=10) {
        lastErrorMsg += F("Connection timeout");
        return false;
    }

    String request = "GET " + apiGetLatestRelease + F(" HTTP/1.0\r\nHost: ") + String(apiHost) + F("\r\nuser-agent: esp32/1.0\r\nX-GitHub-Api-Version: 2022-11-28\r\nAccept: application/vnd.github+json\r\n");
    if (accessToken.length()) request += "Authorization: Bearer " + String(accessToken) + F("\r\n");
    request += F("Connection: close\r\n\r\n");

    httpsClient.print(request);
    retryCounter=0;
    while(!httpsClient.available()) {
        delay(200);
        retryCounter++;
        if (retryCounter > 25) {
            // no response within 5 seconds so quit
            httpsClient.stop();
            lastErrorMsg += F("Response timeout");
            return false;
        }
    }

    while (httpsClient.connected()) {
        String line = httpsClient.readStringUntil('\n');
        // check for success code...
        if (line.startsWith("HTTP")) {
            if (line.indexOf("200 OK") == -1) {
            httpsClient.stop();
            lastErrorMsg += line;
            return false;
            }
        }
        if (line == "\r") {
            // Headers received
            break;
        }
    }

    bool isBody = false;
    char c;
    releaseId="";
    releaseDescription="";
    releaseAssets=0;
    unsigned long dataReceived = 0;

    unsigned long dataSendTimeout = millis() + 12000UL;
    while((httpsClient.available() || httpsClient.connected()) && (millis() < dataSendTimeout)) {
        while(httpsClient.available()) {
            c = httpsClient.read();
            dataReceived++;
            if (c == '{' || c == '[') isBody = true;
            if (isBody) parser.parse(c);
        }
        delay(5);
    }
    httpsClient.stop();
    if (millis() >= dataSendTimeout) {
        lastErrorMsg += "Data timeout (" + String(dataReceived) + F(" bytes)");
        return false;
    }

    lastErrorMsg=F("SUCCESS");

    return true;
}

/**
 * @brief Retrieves the last error message generated by the client.
 * @return A string containing the error description (or "SUCCESS").
 */
String github::getLastError() {
    return lastErrorMsg;
}

/**
 * @brief JSON whitespace handler.
 * @param c The whitespace char.
 */
void github::whitespace(char c) {}

/**
 * @brief JSON handler triggered at start of document.
 */
void github::startDocument() {
    currentArray = "";
    currentObject = "";
}

/**
 * @brief JSON handler triggered for each object key.
 * @param key The string name of the parsed key.
 */
void github::key(String key) {
    currentKey = key;
}

/**
 * @brief JSON handler triggered for each key value.
 * @param value The scalar string value.
 */
void github::value(String value) {
    if (currentKey == "tag_name") releaseId = value;
    else if ((currentKey == "name") && (currentArray=="")) releaseDescription = value;
    else if ((currentKey == "url") && (currentArray=="assets") && (currentObject!="uploader")) assetURL = value;
    else if ((currentKey == "name") && (currentArray=="assets") && (currentObject!="uploader")) assetName = value;

    if (assetURL.length() && assetName.length() && releaseAssets<MAX_RELEASE_ASSETS) {
        // Save the full asset url to the list
        releaseAssetURL[releaseAssets] = assetURL;
        releaseAssetName[releaseAssets++] = assetName;
        assetURL="";
        assetName="";
    }
}

/**
 * @brief JSON handler triggered when exiting an array.
 */
void github::endArray() {
    currentArray = "";
}

/**
 * @brief JSON handler triggered when exiting an object.
 */
void github::endObject() {
    currentObject = "";
}

/**
 * @brief JSON handler triggered at end of document.
 */
void github::endDocument() {}

/**
 * @brief JSON handler triggered when entering an array.
 */
void github::startArray() {
    currentArray = currentKey;
}

/**
 * @brief JSON handler triggered when entering an object.
 */
void github::startObject() {
    currentObject = currentKey;
}
