/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Refactored for v3.0 by Matt McNeill 2026 CB Labs
 *
 * GitHub Client Library - enables checking for latest release and downloading assets to file system
 *
 * https://github.com/gadec-uk/departures-board
 *
 * This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
 * To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
 *
 * Module: lib/githubClient/githubClient.hpp
 * Description: Client to query the GitHub REST API for release information.
 *
 * Exported Functions/Classes:
 * - github: [Class] API client using streaming JSON parser.
 *   - getLatestRelease(): Polls GitHub for release metadata.
 *   - getLastError(): Diagnostic error retrieval.
 */
#pragma once
#include <JsonListener.h>
#include <JsonStreamingParser.h>
#include <md5Utils.hpp>

#define MAX_RELEASE_ASSETS 16   //  The maximum number of release asset details that will be read and stored

class github: public JsonListener {

    private:
        const char* apiHost = "api.github.com";
        String apiGetLatestRelease = "/repos/gadec-uk/departures-board/releases/latest";
        String currentKey = "";
        String currentArray = "";
        String currentObject = "";
        String previousObject = "";

        char lastErrorMsg[128];

        String assetURL;
        String assetName;
        md5Utils md5;

    public:
        String accessToken;
        String releaseId;
        String releaseDescription;
        int releaseAssets;
        String releaseAssetURL[MAX_RELEASE_ASSETS];
        String releaseAssetName[MAX_RELEASE_ASSETS];

        github(String repository, String token);

/**
 * @brief Polls the GitHub API to fetch metadata about the latest release for the repository.
 * @return True if the metadata was successfully fetched and parsed, otherwise false.
 */
        bool getLatestRelease();
        //bool downloadAssetToLittleFS(String url, String filename);

/**
 * @brief Retrieves the last error message generated by the client.
 * @return A string containing the error description (or "SUCCESS").
 */
        const char* getLastError();

/**
 * @brief JSON whitespace handler.
 * @param c The whitespace char.
 */
        virtual void whitespace(char c);

/**
 * @brief JSON handler triggered at start of document.
 */
        virtual void startDocument();

/**
 * @brief JSON handler triggered for each object key.
 * @param key The string name of the parsed key.
 */
        virtual void key(String key);

/**
 * @brief JSON handler triggered for each key value.
 * @param value The scalar string value.
 */
        virtual void value(String value);

/**
 * @brief JSON handler triggered when exiting an array.
 */
        virtual void endArray();

/**
 * @brief JSON handler triggered when exiting an object.
 */
        virtual void endObject();

/**
 * @brief JSON handler triggered at end of document.
 */
        virtual void endDocument();

/**
 * @brief JSON handler triggered when entering an array.
 */
        virtual void startArray();

/**
 * @brief JSON handler triggered when entering an object.
 */
        virtual void startObject();
};
