#!/usr/bin/env python3
import datetime
import os
import subprocess

# Get current time in ByyyyMMddHHmmss format
now = datetime.datetime.now()
timestamp = "B" + now.strftime("%Y%m%d%H%M%S")

# Try to get git hash and check for local modifications (dirty tree)
try:
    git_hash = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'], stderr=subprocess.STDOUT).decode('ascii').strip()
    
    # Check for uncommitted changes (excluding the timestamp file itself to prevent infinite rebuild loops)
    # git diff --quiet returns 1 if there are changes
    is_dirty_working = subprocess.call(['git', 'diff', '--quiet', '--', '.', ':!src/buildTime.cpp']) != 0
    is_dirty_cached = subprocess.call(['git', 'diff', '--cached', '--quiet', '--', '.', ':!src/buildTime.cpp']) != 0
    is_dirty = is_dirty_working or is_dirty_cached
    
    dirty_suffix = "+mod" if is_dirty else ""
    full_serial = f"{timestamp}-{git_hash}{dirty_suffix}"
    git_state = f"{git_hash}{dirty_suffix}"
except Exception:
    full_serial = timestamp
    git_state = "no-git"

# Define target paths
target_dir = os.path.join(os.getcwd(), "src")
target_file = os.path.join(target_dir, "buildTime.cpp")

# Logic: Only update if the Git hash changed OR we are transitioning to/from dirty.
def should_update():
    if not os.path.exists(target_file):
        return True
    
    try:
        with open(target_file, "r") as f:
            content = f.read()
            # If the current git state is already recorded, we are "up to date" 
            # UNLESS it's currently dirty, in which case we don't know if code changed
            # so we check if the timestamp in the file is from TODAY.
            if f'// GIT_STATE: {git_state}' in content:
                if "+mod" not in git_state:
                    return False
                
                # If dirty, check if the file was updated in the last 60 seconds
                # This prevents a tight loop of recompiles during a single 'pio run'
                # but ensures that if you come back later and build, you get a new time.
                mtime = os.path.getmtime(target_file)
                if (datetime.datetime.now().timestamp() - mtime) < 60:
                    return False
    except:
        pass
    return True

if not should_update():
    # Print frozen serial
    with open(target_file, "r") as f:
        for line in f:
            if 'const char* BUILD_TIME' in line:
                old_serial = line.split('"')[1]
                print(f"--- Build Serial (Frozen): {old_serial} ---")
                break
else:
    # Write the implementation file
    with open(target_file, "w") as f:
        f.write("/*\n")
        f.write(" * Departures Board (c) 2025-2026 Gadec Software\n")
        f.write(" * Autogenerated build timestamp implementation.\n")
        f.write(" */\n\n")
        f.write(f"// GIT_STATE: {git_state}\n")
        f.write('#include "buildTime.hpp"\n\n')
        f.write(f'const char* BUILD_TIME = "{full_serial}";\n')
        f.write(f'const char* BUILD_DATE_PRETTY = "{now.strftime("%Y-%m-%d")}";\n')
    
    print(f"--- Build Serial: {full_serial} ---")
