"""
Departures Board (c) 2025-2026 Gadec Software
Refactored for v3.0 by Matt McNeill 2026 CB Labs

https://github.com/gadec-uk/departures-board

This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/

Module: scripts/txt_to_bdf.py
Description: Converts human-readable font dumps (generated by font_decompiler.c) 
             into standard BDF (Glyph Bitmap Distribution Format) source files.
             This allows fonts to be edited in standard font editors and then
             recompiled into the final firmware.

Exported Functions:
- parse_font_txt: Parses metadata and ASCII grids from a .txt dump.
- write_bdf: Generates a BDF file from the parsed character data.
"""

import sys
import re
import os
import glob

def parse_font_txt(filename):
    """
    Parses a specialized font text dump and extracts glyph metadata and bitmaps.
    
    Args:
        filename (str): Path to the .txt dump file.
        
    Returns:
        tuple: (font_name, chars_list) or None if parsing fails.
    """
    with open(filename, 'r') as f:
        lines = f.readlines()
        
    # --- Step 1: Extract Font Metadata ---
    font_name = ""
    for line in lines:
        if line.startswith("Font:"):
            font_name = line.split(":", 1)[1].strip()
            break
            
    if not font_name:
        print(f"No font name found in {filename}")
        return None
        
    chars = []
    
    # --- Step 2: Extract Individual Glyphs ---
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("Character"):
            # Format: 'Character U+XXXX (Char: 'X')'
            m = re.match(r"Character U\+([0-9A-Fa-f]+)", line)
            if not m:
                i += 1
                continue
                
            unicode_val = int(m.group(1), 16)
            
            # The metadata line immediately follows the character header
            i += 1
            meta_line = lines[i].strip()
            # Format: 'Width: W, Height: H, X-Offset: X, Y-Offset: Y, dX: DX'
            meta_m = re.match(r"Width:\s*([-\d]+),\s*Height:\s*([-\d]+),\s*X-Offset:\s*([-\d]+),\s*Y-Offset:\s*([-\d]+),\s*dX:\s*([-\d]+)", meta_line)
            
            if not meta_m:
                i += 1
                continue

            w = int(meta_m.group(1))
            h = int(meta_m.group(2))
            x_off = int(meta_m.group(3))
            y_off = int(meta_m.group(4))
            dx = int(meta_m.group(5))
            
            # Read 'H' lines of ASCII art representing the pixel grid
            grid = []
            for _ in range(h):
                i += 1
                grid.append(lines[i].strip())
                
            chars.append({
                "unicode": unicode_val,
                "w": w,
                "h": h,
                "x_off": x_off,
                "y_off": y_off,
                "dx": dx,
                "grid": grid
            })
            
        i += 1
        
    return font_name, chars

def write_bdf(font_name, chars, out_filename):
    """
    Writes the extracted font data into a standard BDF 2.1 file.
    
    Args:
        font_name (str): The name of the font.
        chars (list): List of glyph dictionaries.
        out_filename (str): Output BDF path.
    """
    if not chars: return
    
    # --- Step 1: Calculate Global Font Bounding Box ---
    max_w = max([c['w'] for c in chars]) if chars else 8
    max_h = max([c['h'] for c in chars]) if chars else 8
    min_x = min([c['x_off'] for c in chars]) if chars else 0
    min_y = min([c['y_off'] for c in chars]) if chars else 0
    
    with open(out_filename, 'w') as f:
        # BDF Global Header
        f.write(f"STARTFONT 2.1\n")
        f.write(f"FONT {font_name}\n")
        f.write(f"SIZE {max_h} 75 75\n")
        f.write(f"FONTBOUNDINGBOX {max_w} {max_h} {min_x} {min_y}\n")
        f.write(f"STARTPROPERTIES 2\n")
        f.write(f"FONT_ASCENT {max_h + min_y}\n")
        f.write(f"FONT_DESCENT {-min_y}\n")
        f.write(f"ENDPROPERTIES\n")
        f.write(f"CHARS {len(chars)}\n")
        
        # --- Step 2: Write Individual Characters ---
        for c in chars:
            f.write(f"STARTCHAR U+{c['unicode']:04X}\n")
            f.write(f"ENCODING {c['unicode']}\n")
            # SWIDTH is scalable width (standardized to 1000-unit square)
            f.write(f"SWIDTH {c['dx'] * 1000 // max_h if max_h else c['dx']} 0\n")
            f.write(f"DWIDTH {c['dx']} 0\n")
            f.write(f"BBX {c['w']} {c['h']} {c['x_off']} {c['y_off']}\n")
            
            f.write("BITMAP\n")
            # Convert ASCII Art ('.', '#') to BDF Hex format
            for row in c['grid']:
                if row:
                    # Convert pixel representation to binary string
                    bin_str = row.replace('.', '0').replace('#', '1')
                    
                    # BDF rows must be padded to the nearest full byte (8 bits)
                    rem = len(bin_str) % 8
                    if rem != 0:
                        bin_str += '0' * (8 - rem)
                    
                    # Convert 8-bit chunks to Hex strings
                    hex_str = ""
                    for j in range(0, len(bin_str), 8):
                        byte_val = int(bin_str[j:j+8], 2)
                        hex_str += f"{byte_val:02X}"
                    f.write(f"{hex_str}\n")
            f.write("ENDCHAR\n")
        f.write("ENDFONT\n")

if __name__ == "__main__":
    # Resolve project paths relative to the script location
    script_dir = os.path.dirname(os.path.realpath(__file__))
    root_dir = os.path.dirname(script_dir)
    
    source_dir = os.path.join(root_dir, "modules", "displayManager", "fonts", "source")
    dest_dir = source_dir
    
    if not os.path.exists(dest_dir):
        os.makedirs(dest_dir)
        
    print(f"Looking for dumps in {source_dir}...")
    txt_files = glob.glob(os.path.join(source_dir, "*.txt"))
    
    # Process all available text dumps
    for txt_file in txt_files:
        print(f"Parsing {os.path.basename(txt_file)}...")
        res = parse_font_txt(txt_file)
        if res:
            font_name, chars = res
            out_file = os.path.join(dest_dir, f"{font_name}.bdf")
            write_bdf(font_name, chars, out_file)
            print(f"  -> Wrote {out_file}")
