/*
 * Departures Board (c) 2025-2026 Gadec Software
 * Autogenerated from layoutDefault.json
 */

#ifndef TFL_LAYOUT_DEFAULT_HPP
#define TFL_LAYOUT_DEFAULT_HPP

#include "../iTflLayout.hpp"

class layoutTflDefault : public iTflLayout {
public:
    layoutTflDefault(appContext* context);
};

#endif // TFL_LAYOUT_DEFAULT_HPP
